---
title: Flow charts in R using DiagrammeR
author: Liang
date: '2018-05-08'
slug: flow-charts-in-r-using-diagrammer
categories:
  - R
tags:
  - R
---


```{r}
library(DiagrammeR)
DiagrammeR("graph LR;
           A-->B;
           B-->C;
           B-->D")
```

```{r}
library(DiagrammeR)
DiagrammeR("graph TB;
    A(Rounded)-->B[Squared];
    B---C{Rhombus!};
    C-->D>flag shape];
    C-->E((Circle));")
```



```{r}
library(DiagrammeR)

DiagrammeR("
  graph TD;
    A[rect]-- add style -->A2[rect + style];
    B{rhombus}---|+ some style|B2{rhombus + style};
    C(rounded);   D((circle)); 
    style A2 fill:#c12,stroke-width:5px;
    style B2 fill:none, stroke-dasharray:10;
")

```

```{r}
library(DiagrammeR)
# workflow of a post graph
DiagrammeR("
  graph TD;
    hw{htmlwidget} -->experiments;
    hw -->content;
    experiments -->RMarkdown
    content -->RMarkdown
    RMarkdown -->|R/knitr|Markdown;
    Markdown -->|Pandoc|HTML;
    HTML -->|git push| Github;
    HTML -->|copy/paste| Squarespace ;
")
```


waiting continue...

## Reference

[Easy Flowcharts and Diagrams](http://timelyportfolio.github.io/buildingwidgets/week01/)




